### DISCUSSION TITLE
Separating fields with Key Pairs/Seperators

### DISCUSSION THREAD

**Discussion by reece394** [WithSecureLabs/chainsaw#177] [Q&A] [answered]
Is there any capability to separate keypair values when creating a chainsaw rule?

I am trying to create a chainsaw rule for PowerShell EventID 400 Events however the output is quite messy as it is all under the Data Field. I have already specified an array index Event.EventData.Data[2] but it would be nice to be able to do something like Event.EventData.Data[2].HostApplication= on key pairs inside the fields if they are consistent. 

There are other logs that would use : instead of = so if there is a way to do this for them as well that would be helpful to know!

What I am aiming to do is split the fields out further so instead of NewEngineState=Available HostApplication=powershell -WindowStyle hidden Invoke-WebRequest -URI URL -outfile EXE etc in a single field. They would be split into their own separate columns. So a NewEngineState Column would have Available in it and a Host Application Column would have powershell -WindowStyle hidden Invoke-WebRequest -URI URL -outfile EXE in it. 

Thanks!

**Comment by alexkornitzer** [comment]
Okay, so to clarify is it that we have something like this:

```
Event:
  EventData:
    Data:
    - Foo
    - Bar
    - NewEngineState=Available HostApplication=powershell -WindowStyle hidden Invoke-WebRequest -URI URL -outfile EXE
```

Then the request is to allow for parsing of the string at index `2`, splitting on space and then looking for key/value pairs?

```
Event:
  EventData:
    Data:
    - Foo
    - Bar
    - NewEngineState=Available
      HostApplication=powershell -WindowStyle hidden Invoke-WebRequest -URI URL -outfile EXE
```

If so that should be doable we just need clear rules on how to split the string as splitting on space will not be sufficient and cause erroneous results.

**Reply by reece394** [reply]
Yes that is exactly what I am after. I know for that specific event it has stuff like \r\n\ or \r\n\t. In that case if possible it might be good to let the user specify what it splits on as that would allow the manipulation of a lot of weirdly formatted logs. \n would be the important one for that event though

**Reply by alexkornitzer** [reply]
Okay, so that should be pretty doable because we already have rough support for this already to handle JSON (https://github.com/WithSecureLabs/chainsaw/blob/master/rules/antivirus/sophos.yml#L28). So we could add a new format type which is `powershell` or potentially we could have it more flexible like `kv` and we can specify delimiters.

```
- name: Foo
  container:
    field: Event.EventData.Data[2]
    format: powershell
  to: Parsed  
```

or

```
- name: Foo
  container:
    field: Event.EventData.Data[2]
    format: kv
    delimiter: ':'
    split: '\r\n'
  to: Parsed  
```

This would then let us match on `Parsed.HostApplication`. I will need to PoC it though cause there is probably something I am forgetting. Lemme know if this would be sufficient and i'll create an issue and add it to my list.

**Reply by reece394** [reply]
Yes I think the second option making it more flexible will be the best option. That sounds perfect for this and it should allow for a lot more logs to be manipulated too rather than restricting it. Thanks for looking into this for me!

**Reply by alexkornitzer** [reply]
No problem, I should have time to implement this on the weekend.

**Reply by alexkornitzer** [reply]
This is done, you able to build from master or is it easier if I push a new build? https://github.com/WithSecureLabs/chainsaw/issues/178

**Reply by reece394** [reply]
Thanks for this! If you could push a new build it would make 100% sure it is built right.

**Reply by alexkornitzer** [reply]
Okay, done as a beta so we can make breaking changes: https://github.com/WithSecureLabs/chainsaw/releases/tag/v2.10.0-beta.0

**Reply by reece394** [reply]
This works great for the most part. It splits well but for some reason it can't handle bigger PowerShell scripts when I was testing it. When I am splitting on HostApplication when I use those it shows up as blank. To be clear though on smaller events it splits fine such as the one below so it does work.

![image](https://github.com/user-attachments/assets/1716f776-41ce-4a25-98f8-08349dc1154a)


This is the rule I am using: 
```
---
title: PowerShell - Engine state is changed from None to Available
group: PowerShell Engine State
description: PowerShell - Engine state is changed from None to Available
authors: 
  - Reece394


kind: evtx
level: info
status: stable
timestamp: Event.System.TimeCreated


fields:
  - name: Event ID
    to: Event.System.EventID
  - name: Channel
    to : Event.System.Channel
  - name: Computer
    to: Event.System.Computer
  - name: HostName
    container:
     field: Event.EventData.Data[2]
     format: kv
     delimiter: "\r\n\t"
     separator: '='
    to: HostName
    from: Event.EventData.Data[2].HostName
  - name: HostVersion
    container:
     field: Event.EventData.Data[2]
     format: kv
     delimiter: "\r\n\t"
     separator: '='
    to: HostVersion
    from: Event.EventData.Data[2].HostVersion
  - name: HostApplication
    container:
     field: Event.EventData.Data[2]
     format: kv
     delimiter: "\r\n\t"
     separator: '='
    to: HostApplication
    from: Event.EventData.Data[2].HostApplication
  - name: PipelineId
    container:
     field: Event.EventData.Data[2]
     format: kv
     delimiter: "\r\n\t"
     separator: '='
    to: PipelineId
    from: Event.EventData.Data[2].PipelineId
  - name: CommandName
    container:
     field: Event.EventData.Data[2]
     format: kv
     delimiter: "\r\n\t"
     separator: '='
    to: CommandName
    from: Event.EventData.Data[2].CommandName
  - name: CommandType
    container:
     field: Event.EventData.Data[2]
     format: kv
     delimiter: "\r\n\t"
     separator: '='
    to: CommandType
    from: Event.EventData.Data[2].CommandType
  - name: ScriptName
    container:
     field: Event.EventData.Data[2]
     format: kv
     delimiter: "\r\n\t"
     separator: '='
    to: ScriptName
    from: Event.EventData.Data[2].ScriptName
  - name: CommandPath
    container:
     field: Event.EventData.Data[2]
     format: kv
     delimiter: "\r\n\t"
     separator: '='
    to: CommandPath
    from: Event.EventData.Data[2].CommandPath
  - name: CommandLine
    container:
     field: Event.EventData.Data[2]
     format: kv
     delimiter: "\r\n\t"
     separator: '='
    to: CommandLine
    from: Event.EventData.Data[2].CommandLine
filter:
  condition: powershell

  powershell:
      Event.System.EventID: 400
      Event.System.Channel: Windows PowerShell

```
This is an example event that shows up as blank when being outputted to CSV. I unfortunately can't give you the original event as it is from a case I was on

```EventData:
    Data:
    - Available
    - None
    - "\tNewEngineState=Available\r\n\tPreviousEngineState=None\r\n\r\n\tSequenceNumber=13\r\n\r\n\tHostName=ConsoleHost\r\n\tHostVersion=5.1.17763.5933\r\n\tHostId=d6266bf9-aaaa-4338-980a-111aaaaaaa\r\n\tHostApplication=C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\powershell.exe -ExecutionPolicy AllSigned -NoProfile -NonInteractive -Command & {$OutputEncoding = [Console]::OutputEncoding =[System.Text.Encoding]::UTF8;$scriptFileStream = [System.IO.File]::Open('C:\\ProgramData\\Microsoft\\Windows Defender Advanced Threat Protection\\DataCollection\\8764.11167324.0.11167324.11167324-98cbc13111b14abe423d11a042fa7acda7c3ed31\\8bf8968b-8445-46aa-9448-9d422afcb22b.ps1', [System.IO.FileMode]::Open, [System.IO.FileAccess]::Read, [System.IO.FileShare]::Read);$calculatedHash = Microsoft.PowerShell.Utility\\Get-FileHash 'C:\\ProgramData\\Microsoft\\Windows Defender Advanced Threat Protection\\DataCollection\\8764.11167324.0.11167324.11167324-98cbc13111b14abe423d11a042fa7acda7c3ed31\\8bf8968b-8445-46aa-9448-9d422afcb22b.ps1' -Algorithm SHA256;if (!($calculatedHash.Hash -eq 'a253760ad6022c52ebd49cfca345454089552e47c907ff2574b19cd0aaaaaaaa')) { exit 323;}; . 'C:\\ProgramData\\Microsoft\\Windows Defender Advanced Threat Protection\\DataCollection\\8764.11167324.0.11167324.11167324-98cbc13111b14abe423d11a042fa7acda7c3ed31\\8bf8968b-8445-46aa-9448-9d422afcb22b.ps1' }\r\n\tEngineVersion=5.1.17763.5933\r\n\tRunspaceId=9962c98a-ffa0-458f-a772-1b3d6cdf5709\r\n\tPipelineId=\r\n\tCommandName=\r\n\tCommandType=\r\n\tScriptName=\r\n\tCommandPath=\r\n\tCommandLine="```

**Reply by alexkornitzer** [reply]
I was quite strict on the parsing of pairs so lemme take that line above and do a quick check. I think we might also need a trim option so we can strip that leading `\t`.

**Reply by alexkornitzer** [reply]
Ah I see the issue, its cause there are multiple `=` in that, lemme tweak the code to only split on the first occurrence.

**Reply by reece394** [reply]
> I was quite strict on the parsing of pairs so lemme take that line above and do a quick check. I think we might also need a trim option so we can strip that leading `\t`.

Yeah I noted this when I was testing and as long as I specified the \t in the rule for the NewEngineState as "\tNewEngineState" it parsed fine so this isn't a major issue.

**Reply by alexkornitzer** [reply, marked as answer]
Okay `beta.1` is up and fixes the issue. I have also added the option to trim whitespace.

```
- name: Embedded
  container:
    field: embedded
    format: kv
    delimiter: "\r\n\t"
    separator: '='
    trim: true       # default false
  to: HostApplication
```
