### ISSUE TITLE
Definition of "logsource" values like product or category.

### ISSUE THREAD

**Issue by Maspital** [WithSecureLabs/chainsaw#107]
Hey,

I am currently using chainsaw + SIGMA to evaluate log datasets and stumbled upon the following issue:
Certain SIGMA rules produce an abnormally high number of false positives, to the point where I suspect that it just triggers on most events. The rule in question is
```yml
title: Sysmon Blocked Executable
id: 23b71bc5-953e-4971-be4c-c896cda73fc2
description: Triggers on any Sysmon file block executable event. Which should indicates a violation of the block policy set
status: experimental
author: Nasreddine Bencherchali
date: 2022/08/16
references:
    - https://medium.com/@olafhartong/sysmon-14-0-fileblockexecutable-13d7ba3dff3e
tags:
    - attack.defense_evasion
logsource:
    product: windows
    category: file_block
detection:
    selection:
        Image: '*'
    condition: selection
falsepositives:
    - Unlikely
level: high
```
I think the problem is that the category in question (`file_block`) is not mapped to anything - where and how can I define this?
In this example, the category should be `file_block` iff `"provider_name": "Microsoft-Windows-Sysmon"` and `event_id: 27`, which would clearly identify the category.

I have a similar problem for several other rules. Am I perhaps misunderstanding how certain things work?

Any help on this would be much appreciated :)

**Comment by FranticTyping** [comment]
Hey @Maspital 

I'm guessing you're running chainsaw with the `sigma-event-logs-all.yml` mapping file. This mapping file does not filter based on provider name or category which means that some Sigma rules (like the file block one you mentioned above) cause a huge number of false positives.

You could either extend the sigma rule to also require a specific event ID (which should cut down the number of FPs), or you could use the `sigma-event-logs-legacy.yml` mapping file instead which supports "Provider" mappings.

I don't think either of these two options will completely solve your issue, but it should reduce the number of FPs that you face.

**Comment by alexkornitzer** [comment]
There is also potential to add category support to the mapping to apply 'x' filter when category 'y' is set. But this would require code enhancements.

**Comment by Maspital** [comment]
Yes, I'm using a modified version of `sigma_event_logs.all` (because winlogbeat likes to name stuff differently). Changing SIGMA rules themselves even slightly is something I would like to avoid because I want to be able to say "this dataset was created with SIGMA vXX" so it can be reproduced easily (though this is probably the easiest solution). In this case the change would be simply, but I wouldn't say I'm competent enough to confidently say that whatever change I intend to do does not change the intended result/logic of a given SIGMA rule :D

Using the legacy mapping file seems like it both has a lot of duplicate entries and prevents any novel alerts from being shown because they are blocked by the manually set filters(?).

Having category support like you mentioned @alexkornitzer would be a really nice and useful feature imo, but I dont know how much effort this would require on your part.

**Comment by alexkornitzer** [comment]
So adding this code wise is pretty easy the challenge comes from how to extend the mapping schema in a clear way, my current thinking is something like this:

```
---
name: Chainsaw's groupless Sigma mappings for Event Logs
kind: evtx
rules: sigma
...

extensions:
  preconditions:
    - for:
        category: file_block
      filter:
        int(EventID): 27
        Provider: Microsoft-Windows-Sysmon
...
groups:
...
```

Where the `for` block can consist of different identifiable fields of a Sigma rule.

**Comment by Maspital** [comment]
That looks great! Assuming knowledge of Sigma rules in general, this is nice and understandable in my opinion.

So this would work for whatever field may be defined within the `logsource` of a rule?

**Comment by alexkornitzer** [comment]
Ah good spot nah I would wanna support things like name too, so it should be this:
```
---
name: Chainsaw's groupless Sigma mappings for Event Logs
kind: evtx
rules: sigma
...

extensions:
  preconditions:
    - for:
        logsource:
          category: file_block
      filter:
        int(EventID): 27
        Provider: Microsoft-Windows-Sysmon
...
groups:
...
```

But awesome, okay i'll see if I can do this when I get time otherwise i'll lob it at someone else :)

**Comment by Maspital** [comment]
Any news regarding this? :) @alexkornitzer

**Comment by alexkornitzer** [comment]
@Maspital can you give the `feature/extensions` branch a try?

**Comment by Maspital** [comment]
Seems to work nicely, at least for the things I tested :+1: I will try it out in more detail tomorrow

**Comment by alexkornitzer** [comment]
Awesome. If it all seems fine tomorrow i'll get that merged in and released.

**Comment by alexkornitzer** [comment]
Thanks for checking that all out. Right so the first one is probably not doable because I don't think I have put support in to handle nested syntax for a filter so this `not(int(EventID))` probably won't work. We would need to upgrade the filter to be a full Tau block with `condition` support, so maybe that can come in later as its not too difficult to add. I should add array support into the `for` block as well but that can for now just be handled with copy paste, at the cost of duplication.

I don't have a ton of time at the moment so I will merge the current work, and then your two above improvements can be added at a later date. For now I will keep this issue open as a reminder.

**Comment by Fuzzdkk** [comment]
Triage note: this was implemented. The `extensions.preconditions` schema Alex sketched out is live in `mappings/sigma-event-logs-all.yml` and parsed in `src/hunt.rs`. The `for: logsource.category: ...` form Alex landed on is exactly what's in the file:

```yaml
extensions:
  preconditions:
    - for:
        logsource.category: process_creation
      filter:
        - Provider: Microsoft-Windows-Sysmon
          int(EventID): 1
        - Provider: Microsoft-Windows-Security-Auditing
          int(EventID): 4688
```

Multiple categories covered (process_creation, network_connection, image_load, driver_load, etc.), so the original FP problem this was meant to address is handled in the default mapping. @Maspital probably safe to close unless you're hitting something the precondition system doesn't cover.

**Comment by alexkornitzer** [comment]
@Fuzzdkk the reason this issue is still open was as a reminder about the 2 additional feature requests:

1. negation operations, i.e. would this still not work (off the top of my head I can't remember, would need to check the code):

```yaml
extensions:
  preconditions:
    - for:
        logsource.category: process_creation
      filter:
          not(int(EventID)): 4688
```

2. Additionally the preconditions needs to be extended with the ability to only apply to some Sigma rules.

**Comment by Fuzzdkk** [comment]
On (1): doesn't work today. The precondition `filter:` is deserialized via `crate::ext::tau::deserialize_expression` (hunt.rs:38), which goes straight to tau's `parse_identifier`. The `not(...)` and `!` prefix handling lives in `parse_kv` in `src/ext/tau.rs`, which preconditions skip. So `not(int(EventID)): 4688` parses as a literal field key called `not(int(EventID))` and never matches.

Should be a small change: a precondition-specific deserializer that reuses the `parse_kv` path the same way Sigma rule fields do. There are no precondition tests either, worth adding some at the same time.

On (2): partially possible already. `for_` matches against anything `Sigma::Document::find` exposes (sigma.rs:44-72), so `for: { id: "abc-..." }` or `for: { title: "Some Rule" }` works for individual rules today. What's missing is list-of-rules in a single precondition (`for: { id: [a, b] }`) and the FIXME at hunt.rs:208-209: when two preconditions both match the same rule, the second silently overwrites the first via `preconds.insert(...)`. Probably wants AND.

Want me to take a stab at the negation one?

**Comment by alexkornitzer** [comment]
Yep I am happy with that approach, `parse_kv` is what the search feature uses for its `-t` arguments. Using that function the syntax would be `int(EventID): !4688` which is fine.

**Comment by alexkornitzer** [comment]
As noted in the above PR, I changed my mind on this and went with an approach that reduces code and tau-chainsaw language fracturing, so we can now do:

```yaml
extensions:
  preconditions:
    - for:
        logsource.category: process_creation
      filter:
        not int(EventID): 1337
```
