### ISSUE TITLE
[Feature Request] Support for "contains",  "|" and "all" in both chainsaw and sigma rules

### ISSUE THREAD

**Issue by reece394** [WithSecureLabs/chainsaw#149]
I was wanting to write some Service Installation related rules for chainsaw and I tried doing the following as a test:

```
filter:
  Event.System.EventID: 7045
  Event.EventData.ServiceName|contains: 
    - servicenamehere
```
I checked the code [here](https://github.com/WithSecureLabs/chainsaw/blob/master/src/rule/chainsaw.rs) and it appears that there is no support for using contains for chainsaw rules specifically. 

I then checked the sigma code [here](https://github.com/WithSecureLabs/chainsaw/blob/master/src/rule/sigma.rs) and it appears to support "contains" as well as "all" but when testing with [this](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/builtin/system/service_control_manager/win_system_cobaltstrike_service_installs.yml) rule it refuses to load. Attempts to modify it to just use ImagePath|contains does not work either. 

I noticed that "|" is marked as unsupported in the sigma code is that why it is failing to work?

I would be grateful if this feature could be added as powerful rules could be created with this.

Thanks for your work on this tool as always!

**Comment by alexkornitzer** [comment]
Hey,

So Chainsaw rules use Tau Engine syntax (https://github.com/WithSecureLabs/tau-engine) and not that of Sigma rules, so contains would be done like this:
```
filter:
  Event.EventData.ServiceName:
    - *servicenamehere*
```
While `all` can be achieved like so:
```
filter:
  all(Event.EventData.ServiceName):
    - *foo*
    - *bar*
```

Chainsaw converts Sigma rules into Tau Engine syntax and does a lot of preprocessing before finally parsing them. `|` is supported but is handled in the preprocessing stage to extract the modifiers so they can be applied in a Tau like way (https://github.com/WithSecureLabs/chainsaw/blob/master/src/rule/sigma.rs#L551). It appears to be linting fine to me:
```
$ chainsaw --no-banner lint --kind sigma /tmp/sigma/rules/windows/builtin/system/service_control_manager/win_system_cobaltstrike_service_installs.yml
[+] Validating as sigma for supplied detection rules...
[+] Validated 1 detection rules out of 1
```

**Comment by reece394** [comment]
Thanks for that information. It is my fault that I thought chainsaw used the sigma syntax for both sets of rules as the .yml files look similar.  I have used the below as a test:

```
---
title: Service Installation Test
group: Service Installation 
description: This is a Test
authors:
  - reece394


kind: evtx
level: critical
status: stable
timestamp: Event.System.TimeCreated


fields:
  - name: Event ID
    to: Event.System.EventID
  - name: Record ID
    to: Event.System.EventRecordID
  - name: Computer
    to: Event.System.Computer
  - name: Service Name
    to: Event.EventData.ServiceName
  - name: Service File Name
    to: Event.EventData.ImagePath
  - name: Service Type
    to: Event.EventData.ServiceType
  - name: Service Start Type
    to: Event.EventData.StartType  
  - name: Service Account
    to: Event.EventData.AccountName  

filter:
  Event.System.EventID: 7045
  Event.EventData.ServiceName: 
    - *Parallels*
    - *Arsenal*
    - PrlVssProvider
```
When doing this I get "No valid detection rules were found in the provided paths" with just that rule enabled. 
Additionally I used System_7045_namedpipe_privesc.evtx from EVTX_ATTACK_SAMPLES and modified the sigma rule I mentioned earlier to simplify testing as I don't have a CobaltStrike EVTX on hand for testing. It does load as you pointed out however no matches are generated from it even though clearly %COMSPEC% is in the ImagePath

```
title: CobaltStrike Service Installations - System
id: 5a105d34-05fc-401e-8553-272b45c1522d
status: test
description: Detects known malicious service installs that appear in cases in which a Cobalt Strike beacon elevates privileges or lateral movement
references:
    - https://www.sans.org/webcasts/119395
    - https://www.crowdstrike.com/blog/getting-the-bacon-from-cobalt-strike-beacon/
    - https://thedfirreport.com/2021/08/29/cobalt-strike-a-defenders-guide/
author: Florian Roth (Nextron Systems), Wojciech Lesicki
date: 2021/05/26
modified: 2022/11/27
tags:
    - attack.execution
    - attack.privilege_escalation
    - attack.lateral_movement
    - attack.t1021.002
    - attack.t1543.003
    - attack.t1569.002
logsource:
    product: windows
    service: system
detection:
    selection_id:
        Provider_Name: 'Service Control Manager'
        EventID: 7045
    selection2:
        ImagePath|contains:
            - '%COMSPEC%'
    condition: selection_id and selection2
falsepositives:
    - Unknown
level: critical
```
